### ISSUE TITLE
how to run the docker ?

### ISSUE THREAD

**Issue by changchichung** [birchwood-langham/ubuntu-base-atom#1]
any special volume ?  expose ports ?  how to start atom ???

**Comment by guoguojin** [comment]
**NOTE**: This is a very old project that I haven't touched in a long time and was done for personal use and experimentation. I cannot support this, beyond the information provided below. Caveat Emptor.

I have not been able to test this, and have taken the information from another project: 

https://github.com/birchwood-langham/ubuntu-go-atom


On Linux:

`docker run -dit --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.atom-docker:/home/user/.atom --name=atom guoguojin/ubuntu-base-atom:latest`

You need to allow xhost access in order for the application in the container to access your host X server.

If you want to expose a local folder with your code to the container, you need to also add -v /path/to/your/code:/home/user/whatever-your-desired-folder-name-is.

On MacOS:

The steps are a bit more complex and best put into a bash script, you will need to have  XQuartz installed to provide a X Windows system to display the application:

```bash
#!/bin/bash

# Start Quartz
open -a XQuartz

# Obtain the IP address of the container
IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')

# Allow connections to the X server from the given IP
xhost + $IP

# Give it a couple of seconds to initiate properly
sleep 1

# Start the docker container
docker run -dit --rm -e DISPLAY=$IP:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.atom-docker:/home/user/.atom --name=atom birchwoodlangham/ubuntu-base-atom:latest
```

This worked when I originally built everything, however it hasn't been tested since, so YMMV.

Hope that helps. 

Additionally, this isn't the best way to do things any more in my opinion. For a learning, it was interesting, but if you want to create a development environment inside of Docker and then be able to access it anywhere, I would recommend looking at:

https://github.com/cdr/code-server

Which is the open source version of Visual Studio Code that you can deploy as a server inside docker and then access using a web browser.

If you prefer something like the Jetbrains toolchain, then there's the projector project that allows you to run IntelliJ and other Jetbrains projects in a browser and there are example of setting it up as a docker image:

https://github.com/JetBrains/projector-server
